### ISSUE TITLE
Version of CAM and DENM messages

### ISSUE THREAD

**Issue by EmmaPlf** [riebl/ros_etsi_its_msgs#1]
Hi ! Thank you for this repository, it's very helpful. 
I would like to know which version of CAM and DENM messages did you use please ?

Best regards

**Comment by riebl** [comment]
Hi @EmmaPlf,

This repository contains only the ROS message equivalents of CAMs and DENMs, which are originally encoded according to ASN.1 UPER. I want to point out that ROS messages and those UPER encoded messages are not binary compatible.
We have some glue code that can translate between those ROS messages this ros_etsi_its_msgs repository and asn1c data structures as employed by Vanetza. Unfortunately, this glue code is not yet publicly available as of today.
Vanetza currently supports CAMs as per EN 302 637-2 v1.4.1 and DENMs as per EN 302 637-3 v1.3.1.

**Comment by EmmaPlf** [comment]
Ok thank you very much !
